### ISSUE TITLE
asql error

### ISSUE THREAD

**Issue by HassanRamos** [ninacoder-info/music-engine-web-wiki#1]
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json DEFAULT NULL,
  `twitter` varchar(300) DEFAULT NULL,
  `approved` tinyint(1' at line 16

**Comment by ninacoder-info** [comment]
Hi you got this error while installing script?

**Comment by ninacoder-info** [comment]
If is the installation problem, could you copy this file into folder database/migrations/ and try to reinstall script?

[2020_09_14_055118_create_artist_requests_table.php.zip](https://github.com/ninacoder-info/music-engine-web-wiki/files/5323569/2020_09_14_055118_create_artist_requests_table.php.zip)
