### ISSUE TITLE
Sound files aren't playing for some reason.

### ISSUE THREAD

**Issue by ONEcorp** [ninacoder-info/music-engine-web-wiki#2]
Heyo! I just recently come across a fatal error that doesn't allow any sound to play at all in the engine. Wonder what's causing this.
![Screen Shot 2020-10-29 at 10 20 06 AM](https://user-images.githubusercontent.com/73425398/97532719-626af200-19d0-11eb-8671-f32da21c3523.png)
Thanks!

**Comment by ninacoder-info** [comment]
Hi can you show the site domain name url?

**Comment by ONEcorp** [comment]
Here you go!
**(https://songin.ml/)**

Thanks!

**Comment by ninacoder-info** [comment]
Hi just release new version, can you follow this to update ?

https://github.com/ninacoder-info/music-engine-web-wiki/wiki/Upgrade-your-site
