### ISSUE TITLE
Possibility of new functions?

### ISSUE THREAD

**Issue by damovear** [ninacoder-info/music-engine-web-wiki#3]
Hello! I really like the script you have. Thanks for creating it!

There are, however, some functions that would be IDEAL to have implemented.

SORT METHODS when creating a channel:
It is true that we can create channels and give it the type of content we want, but would it be possible to give it limits? For example, only show artists of a certain genre, or songs of a certain mood. Maybe albums with a certain tag? Adding a random order to this area wouldn't be bad either.

TAG posiblities:
I have seen that artists can have "moods" and "genres". Wouldn't it be possible to add one more free-form field? For example, for my personal project, I would love to be able to create a field called "Location", that way I create channels of various artists, of a certain location.

ADD SOCIAL NETWORK PAGES:
It is true that your platform is a social network in itself, but don't you think it would be convenient for each artist to be able to put their own links to other pages or social networks?

AND THIS IS MORE A QUESTION THAN AN ADDED
It is true that you can add an artist's biography but ... where is it shown?

Thanks for the attention. I really hope that you can fulfill my order and make it the best script in the world.

See you.

**Comment by ninacoder-info** [comment]
Thanks, noticed and will add in near feature
